### ISSUE TITLE
.Net 8

### ISSUE THREAD

**Issue by kevon-vems** [maacpiash/minimal-api-jwt-auth#1]
I respectfully ask it it is possible for you to update this to .Net 8?

I'm having trouble getting the older version to run.

**Comment by maacpiash** [comment]
After the release of .NET 8, I thought this project was no longer relevant or necessary, since they added [Identity API endpoints](https://learn.microsoft.com/en-au/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-8.0). Now, that Identity API endpoints do not use JWT, but a different format of token powered by [ASP.NET Core Data Protection](https://learn.microsoft.com/en-au/aspnet/core/security/data-protection/introduction?view=aspnetcore-8.0).

Since you asked for this project in .NET 8, I will start working on it.

**Comment by ghost** [comment]
Thank you.  I reviewed the link to the core data protection, and it does not seem to be a replacement for jwt

**Comment by maacpiash** [comment]
I understand that it has been a _comically_ long time. My sincere apologies – I was quite busy with my masters degree.

Our next stop: .NET 9 🙌🏽

#3
